### ISSUE TITLE
Create an extension for `string.Equals` to simplify ignoring case.

### ISSUE THREAD

**Issue by tacosontitan** [tacosontitan/Mauve#21]
Imagine you need to compare two strings `a` and `b` and you want to do this in a manner that ignores casing. Currently, this requires verbose code that, while clear, can seem daunting to junior and even some mid-level developers:
```csharp
string a = "this-is-a-test";
string b = "THIS-IS-A-TEST";
string result = a.Equals(b, StringComparison.InvariantCultureIgnoreCase) ?
    "`a` and `b` are equal." :
    "`a` and `b` are NOT equal.";

Console.WriteLine(result);
```
It has been my experience that a shorter method is preferred which can be easily written and understood by all developers:
```csharp
string a = "this-is-a-test";
string b = "THIS-IS-A-TEST";
string result = a.Equals(b, ignoreCase: true) ?
    "`a` and `b` are equal." :
    "`a` and `b` are NOT equal.";

Console.WriteLine(result);
```
The extension method that provides this functionality should be defined in the namespace `Mauve.Extensibility` and contained in a file named `StringExtensions.cs` where the containing class name is the same.

***Note**: The `StringComparison` parameter to `Equals` should be either `InvariantCulture` or `InvariantCultureIgnoreCase` respective to the value for `ignoreCase`.*

**Comment by Arkadiusz123** [comment]
I'd like to take care of that

**Comment by tacosontitan** [comment]
> I'd like to take care of that

Thank you for your contribution; let me know if you have any questions!
