### ISSUE TITLE
Create an extension for `string.Contains` to ignore casing.

### ISSUE THREAD

**Issue by tacosontitan** [tacosontitan/Mauve#22]
Imagine you need have two strings `a` and `b` and you need to determine if `a` contains `b` in a manner that ignores casing. Currently, this requires verbose code that, while clear, can seem daunting to junior and even some mid-level developers:
```csharp
string a = "this-is-a-test";
string b = "TEST";
string result = a.Contains(b, StringComparison.InvariantCultureIgnoreCase) ?
    "`a` contains `b`." :
    "`a` does NOT contain `b`.";

Console.WriteLine(result);
```
It has been my experience that a shorter method is preferred which can be easily written and understood by all developers:
```csharp
string a = "this-is-a-test";
string b = "TEST";
string result = a.Contains(b, ignoreCase: true) ?
    "`a` contains `b`." :
    "`a` does NOT contain `b`.";

Console.WriteLine(result);
```
The extension method that provides this functionality should be defined in the namespace `Mauve.Extensibility` and contained in a file named `StringExtensions.cs` where the containing class name is the same.

***Note**: The `StringComparison` parameter to `Contains` should be either `InvariantCulture` or `InvariantCultureIgnoreCase` respective to the value for `ignoreCase`.*

**Comment by pizzamnchr** [comment]
I'm on it :)

**Comment by tacosontitan** [comment]
> I'm on it :)

Thank you for your contribution; let me know if you have any questions!

**Comment by tacosontitan** [comment]
@pizzamnchr are you still working on this?

**Comment by pizzamnchr** [comment]
I'll be finishing this up after classes tomorrow :)

**Comment by tacosontitan** [comment]
> I'll be finishing this up after classes tomorrow :)

Sounds great! Thanks again for your contribution!

**Comment by pizzamnchr** [comment]
Finished! So I have my changes on a different branch (branched off main) + it doesn't look I can push my changes to it, should I be doing something different? Like pushing to the main branch, etc. Thanks :)

**Comment by pizzamnchr** [comment]
Finished, but it looks like I can't push my commit as I don't have permission? :(

**Comment by tacosontitan** [comment]
> Finished, but it looks like I can't push my commit as I don't have permission? :(
> 
> Error encountered while pushing to the remote repository: Git failed with a fatal error. Git failed with a fatal error. Could not read from remote repository.
> 
> Please make sure you have the correct access rights and the repository exists.

You'll need to fork the repository and make the change in your fork. Then create a pull request back to this repository with your changes. :)

**Comment by pizzamnchr** [comment]
Roger that!
